apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: hockey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hockey-server
  namespace: hockey
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  hockey-server
  template:
    metadata:
      labels:
        app:  hockey-server
    spec:
      containers:
        - name:  hockey-server
          image: hockey-server:0.0.2
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: udp
              containerPort: 8081
              protocol: UDP
          env:
            - name: HTTP_ADDRESS
              value: ":8080"
            - name: UDP_ADDRESS
              value: ":8081"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-hockey-server
  namespace: hockey
  labels:
    app: hockey-server
spec:
  type: ClusterIP
  selector:
    app: hockey-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: udp
      protocol: UDP
      port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hockey-nginx-ingress
  namespace: hockey
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hockey.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-hockey-server
            port:
              name: http
            
