apiVersion: v1
kind: Service
metadata:
  name: svc-hockey-server
  namespace: hockey
  labels:
    app: hockey-server
spec:
  type: ClusterIP
  selector:
    app: hockey-server
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.containerPortHTTP }}
      targetPort: {{ .Values.containerPortHTTP }}
    - name: udp
      protocol: UDP
      port: {{ .Values.containerPortUDP }}
      targetPort: {{ .Values.containerPortUDP }}
